### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by midorikocak** [rstacruz/rehype-sectionize-headings#1]
Hello,

I am trying to use it as a plugin, but cannot manage it somehow.

Here is the error I receive:

```
    Module build failed (from ./src/template-loader.js):
    TypeError: Cannot read property 'reduce' of undefined
        at wrapHeadings (/Users/midori_kocak/src/ids-styles/node_modules/rehype-sectionize-headings/lib/wrap_headings.js:40:32)
        at wrapH2 (/Users/midori_kocak/src/ids-styles/node_modules/rehype-sectionize-headings/lib/index.js:101:37)
        at _default (/Users/midori_kocak/src/ids-styles/node_modules/rehype-sectionize-headings/lib/index.js:79:10)
        at Object.exports.default (/Users/midori_kocak/src/ids-styles/src/template-loader.js:107:22)
     @ ./src/docs.js 1:1952-2012 1:2741-2747
```

Thanks

**Comment by rstacruz** [comment]
Thanks for the report. How are you using it - can we see a code sample?
